<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container16xWDzD\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container16xWDzD/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container16xWDzD.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container16xWDzD\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container16xWDzD\appAppKernelProdContainer([
    'container.build_hash' => '16xWDzD',
    'container.build_id' => '86efcdb7',
    'container.build_time' => 1719096750,
], __DIR__.\DIRECTORY_SEPARATOR.'Container16xWDzD');
